### ISSUE TITLE
DPO training

### ISSUE THREAD

**Issue by xinbowu2** [ajyl/dpo_toxic#1]
Thanks for this repo! I am wondering if there are codes for performing the DPO on the pairwise toxic data.

**Comment by ajyl** [comment]
Hello! I used this repo - https://github.com/eric-mitchell/direct-preference-optimization
I will try to find time to clean up and push my training script for DPO within the next week or two, but the attached repo is pretty well organized and documented, I imagine you could get up and running within an hour or two.

**Comment by ajyl** [comment]
Uploaded training script - sorry for delay!

**Comment by xinbowu2** [comment]
Sorry, I just saw the updates. Thanks so much!

ajyl ***@***.***>于2024年3月5日 周二08:51写道：
