### ISSUE TITLE
Probe.pt tensor and Mistral 7b Model Tensor Dimension Mismatch (1024 vs 4096)

### ISSUE THREAD

**Issue by czheng17** [ajyl/dpo_toxic#2]
I would like to express my deepest gratitude for your open source code. Your work is solid, and I deeply appreciate your contribution to the community.

I have been attempting to replicate your work using the Mistral model, but I've encountered a challenge related to tensor dimensions. Specifically, the `probe.pt` tensor you provided is of 1024 dimensions, whereas the Mistral model operates with tensors of 4096 dimensions. This discrepancy has led to an issue of incompatible tensor dimensions.

As the code for training `probe.pt` has not been made public, I was wondering if it would be possible for you to provide a version of `probe.pt` with 4096 dimensions? Such assistance would be very helpful to us and likely benefit others facing similar challenges.

**Comment by ajyl** [comment]
Hello! This is the code I used to train our probe: https://github.com/uber-research/PPLM/blob/master/run_pplm_discrim_train.py

I hope that helps!
