### ISSUE TITLE
code for dpo leading to a drop in activations for the toxic vectors

### ISSUE THREAD

**Issue by lucywang720** [ajyl/dpo_toxic#3]
I didn't find the code for dpo that you research in your paper in this repo, could you please give me a link for that? I would be highly appreciate for that.

**Comment by ajyl** [comment]
Are you referring to this? https://github.com/ajyl/dpo_toxic/blob/main/toxicity/figures/activation_drop.sync.ipynb

**Comment by lucywang720** [comment]
thank you very much. it's my negligence that I didn't look up this folder
