### ISSUE TITLE
Un aligning DPO

### ISSUE THREAD

**Issue by r01ex-ai** [ajyl/dpo_toxic#5]
I couldn't find the code for dpo unaligning in section 5.3 in the paper in this repo. Would highly appreciate that.

Also, maybe I'm understanding it wrong but I wonder how 10x ing the MLP_key vector that promote toxic MLP_v neurons recover toxic behaviour. Isn't dot(MLP_key vector, residual stream) already negative after DPO?

**Comment by ajyl** [comment]
Sorry for the late response. Can you try `toxicity/eval_interventions/unalign.py`?

**Comment by r01ex-ai** [comment]
Thanks for the update. Turns out dot(MLP_key vector, residual stream) that actually contributed to toxic token isn't actually negative after DPO, but IS lower than before. Also, other toxic neurons (those that didn't contribute to the original prediction anyway) activation also went down. Resulting mean decrease in toxic activation seen in figure 5 in the paper.
