### ISSUE TITLE
train_dpo/train.py  toxicity module

### ISSUE THREAD

**Issue by Thecommonirin** [ajyl/dpo_toxic#6]
Running train.py has encountered a problem with the toxicity module not importing correctly

**Comment by ajyl** [comment]
Can you share a traceback?

**Comment by Thecommonirin** [comment]
> Can you share a traceback?

![image](https://github.com/user-attachments/assets/9597df3e-b38d-4350-afbc-e1baa1e4890f)

We can run it after changing it to:

    import toxicity.train_dpo.trainers as trainers
    TrainerClass = getattr(trainers, config.trainer)
    print(f"Creating trainer on process {rank} with world size {world_size}")
    trainer = TrainerClass(
        policy,
        config,
        config.seed,
        config.local_run_dir,
        reference_model=reference_model,
        rank=rank,
        world_size=world_size,
    )

    trainer.train_loop()
