### ISSUE TITLE
missing configuration in DPO training

### ISSUE THREAD

**Issue by hz0567** [ajyl/dpo_toxic#7]
""  File "/root/hz/dpo_toxic/toxicity/train_dpo/trainers.py", line 463, in get_batch_metrics
    if loss_config.kl_gamma > 0:
omegaconf.errors.ConfigAttributeError: Key 'kl_gamma' is not in struct
    full_key: loss.kl_gamma
    object_type=dict
""

Hi, thanks for sharing your code. I tried to reproduce the DPO training experiment. But it seems like some configurations are missing in the dpo.yaml.

**Comment by ajyl** [comment]
Hmm, odd. `kl_gamma` is deprecated - can you try again with my recent push?

**Comment by hz0567** [comment]
Yes, thanks.
